-- Если столбец существует мы сделаем безопасное ALTER COLUMN и защитим от несовместимых данных пропущена намеренно,
-- при ошибке ALTER нам можно воспользоваться временными колонками;
/* Тут безопасно изменяется типы и ограничения колонок в таблицах, делая структуру базы данных более надёжной, гибкой и
корректной для бизнес-логики, проверяется наличие каждой колонки перед изменением.*/
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Bicycle' AND COLUMN_NAME='Brand')
    ALTER TABLE dbo.Bicycle ALTER COLUMN Brand VARCHAR(100) NOT NULL;
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Bicycle' AND COLUMN_NAME='RentPrice')
    ALTER TABLE dbo.Bicycle ALTER COLUMN RentPrice MONEY NOT NULL;

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Client' AND COLUMN_NAME='Name')
    ALTER TABLE dbo.Client ALTER COLUMN Name VARCHAR(100) NOT NULL;
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Client' AND COLUMN_NAME='PhoneNumber')
    ALTER TABLE dbo.Client ALTER COLUMN PhoneNumber VARCHAR(30) NULL;
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Client' AND COLUMN_NAME='Country')
    ALTER TABLE dbo.Client ALTER COLUMN Country VARCHAR(100) NULL;

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Staff' AND COLUMN_NAME='Name')
    ALTER TABLE dbo.Staff ALTER COLUMN Name VARCHAR(100) NOT NULL;
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Staff' AND COLUMN_NAME='HireDate')
    ALTER TABLE dbo.Staff ALTER COLUMN HireDate DATETIME2 NULL;

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Detail' AND COLUMN_NAME='Brand')
    ALTER TABLE dbo.Detail ALTER COLUMN Brand VARCHAR(100) NOT NULL;
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Detail' AND COLUMN_NAME='Type')
    ALTER TABLE dbo.Detail ALTER COLUMN Type VARCHAR(100) NOT NULL;
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Detail' AND COLUMN_NAME='Name')
    ALTER TABLE dbo.Detail ALTER COLUMN Name VARCHAR(100) NOT NULL;
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Detail' AND COLUMN_NAME='Price')
    ALTER TABLE dbo.Detail ALTER COLUMN Price MONEY NOT NULL;

GO
