-- Процесс создания таблицы
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Bicycle' AND TABLE_SCHEMA='dbo')
BEGIN
CREATE TABLE dbo.Bicycle
(
   Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
   Brand VARCHAR(100) NOT NULL,
   RentPrice MONEY NOT NULL
);
PRINT 'Создана таблица Bicycle';
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Client' AND TABLE_SCHEMA='dbo')
BEGIN
CREATE TABLE dbo.Client
(
   Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
   Name VARCHAR(100) NOT NULL,
   Passport VARCHAR(50) NOT NULL,
   PhoneNumber VARCHAR(30) NULL,
   Country VARCHAR(100) NULL
);
PRINT 'Создана таблица Client';
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Staff' AND TABLE_SCHEMA='dbo')
BEGIN
CREATE TABLE dbo.Staff
(
   Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
   Name VARCHAR(100) NOT NULL,
   Passport VARCHAR(50) NOT NULL,
   HireDate DATETIME2 NULL
);
PRINT 'Создана таблица Staff';
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Detail' AND TABLE_SCHEMA='dbo')
BEGIN
CREATE TABLE dbo.Detail
(
   Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
   Brand VARCHAR(100) NOT NULL,
   Type VARCHAR(100) NOT NULL,
   Name VARCHAR(100) NOT NULL,
   Price MONEY NOT NULL
);
PRINT 'Создана таблица Detail';
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DetailForBicycle' AND TABLE_SCHEMA='dbo')
BEGIN
CREATE TABLE dbo.DetailForBicycle
(
   BicycleId INT NOT NULL,
   DetailId INT NOT NULL
);
PRINT 'Создана таблица DetailForBicycle';
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'ServiceBook' AND TABLE_SCHEMA='dbo')
BEGIN
CREATE TABLE dbo.ServiceBook
(
   Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
   BicycleId INT NOT NULL,
   DetailId INT NOT NULL,
   Date DATETIME2 NOT NULL,
   Price MONEY NOT NULL,
   StaffId INT NOT NULL
);
PRINT 'Создана таблица ServiceBook';
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'RentBook' AND TABLE_SCHEMA='dbo')
BEGIN
CREATE TABLE dbo.RentBook
(
   Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
   Date DATETIME2 NOT NULL,
   DurationHours INT NOT NULL,
   Paid BIT NOT NULL,
   BicycleId INT NOT NULL,
   ClientId INT NOT NULL,
   StaffId INT NOT NULL
);
PRINT 'Создана таблица RentBook';
END
GO



